Docs: add database1.md
Gabozago-Study/CS-Gabozago pull request #14
Opened 2023-07-30 12:05 UTC by HJ0216

## 개요
Docs: add database1.md

## 작업사항
database1.md 파일 작성

## 변경사항

2023-07-30 13:26 UTC, busymidnight approved these changes

2023-07-30 14:26 UTC, busymidnight requested changes

2023-07-30 14:26 UTC, busymidnight commented on Database/database1.md
> +        * 기본키 (Primary Key) : 후보키에서 특별히 선정된 키로 중복된 값과 Null값을 갖을 수 없음
갖을 수 없음 -> 가질 수 없음

2023-07-30 14:28 UTC, busymidnight requested changes

2023-07-30 14:28 UTC, busymidnight commented on Database/database1.md
> +    * 기본키(Primary Key)는 중복된 값을 갖을 수 없으며 Null값이 올 수 없음
갖을 수 없음 -> 가질 수 없음 으로 변경해주세요!

2023-07-30 14:59 UTC, leemyunga approved these changes

2023-07-30 14:59 UTC, leemyunga commented on Database/database1.md
> +    * 트리거를 과도하게 사용한다면 복잡한 상호 의존성이 생김
* 사용시 주의 사항
  * 트리거 내에서 같은 테이블의 데이터를 변경하는 DML 문을 실행하는 경우 무한 루프에 빠질 수 있다. 예를 들어 Insert 이벤트에 대한 Trigger로 Insert 이벤트가 실행 된다면 무한 루프에 빠지게 됨
  
이 내용도 포함되면 좋겠습니당

2023-07-30 23:43 UTC, HJ0216 commented on Database/database1.md
> +        * 기본키 (Primary Key) : 후보키에서 특별히 선정된 키로 중복된 값과 Null값을 갖을 수 없음
네! 수정 완료하였습니다!

2023-07-30 23:44 UTC, HJ0216 commented on Database/database1.md
> +    * 기본키(Primary Key)는 중복된 값을 갖을 수 없으며 Null값이 올 수 없음
네! 수정 완료하였습니다!

2023-07-30 23:44 UTC, HJ0216 commented on Database/database1.md
> +    * 트리거를 과도하게 사용한다면 복잡한 상호 의존성이 생김
네! 추가 완료하였습니다!

2023-07-31 02:39 UTC, busymidnight approved these changes

2023-07-31 02:39 UTC, merged