Docs: add database2.md
Gabozago-Study/CS-Gabozago pull request #15
Opened 2023-07-30 14:44 UTC by leemyunga

## 개요
Docs: add database2.md

## 작업사항
database2 작성

## 변경사항

2023-07-30 15:16 UTC, busymidnight requested changes

2023-07-30 15:16 UTC, busymidnight commented on Database/database2.md
> +  * Exclusive Lock / Write Lcok 베타락
베타락 -> 배타락 입니다!

2023-07-30 15:16 UTC, busymidnight commented on Database/database2.md
> +
트랜잭션 사용시 주의사항이 추가되면 좋겠습니다.
예) 
**주의사항**
 * 최소한의 코드에 적용하는 것이 좋음
 * DB 커넥션의 수는 제한적 -> 커넥션이 부족해 대기할 수 있음

2023-07-30 15:16 UTC, busymidnight commented on Database/database2.md
> +  * 공유락끼리는 블로킹이 발생하지 않지만, 베타락은 블로킹을 발생
베타락 -> 배타락 입니다!

2023-07-30 15:55 UTC, busymidnight approved these changes

2023-07-31 00:21 UTC, HJ0216 requested changes

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +### Nomarlization 정규화
Nomarlization → Normalization
확인 부탁드리겠습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +  * 테이블이 단순해지고 관리 효율성이 증가되나 데이터의 일관성이나 무결성이 저장되지 않을 수 있음
문맥 상 저장이라는 표현보다는 유지, 보장이라는 단어가 어울릴 것 같아서 확인 부탁드리겠습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +    * SERIALIZABLE : 한 트랜잭션이 COMMIT 될떄까지 다른 트랜잭션은 CRUD 불가
떄 → 때
확인 부탁드리겠습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +  *  연산
마크다운 문법 확인 부탁드리겠습니다!
Preview에서 목차 형식으로 나오지 않습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +  *  주의사항
마크다운 문법 확인 부탁드리겠습니다!
Preview에서 목차 형식으로 나오지 않습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +    * 다른 트랜잭션들이 읽기나 쓰기 작업을 할 수 없도록 허용하지 않고, 해당 데이터를 독점적으로 사용하도록 허용하는 락
읽기나 쓰기 작업을 할 수 없도록 허용하지 않고
→ 읽기나 쓰기 작업을 할 수 없도록 하고
내용 확인 부탁드리겠습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +    * 정 트랜잭션이 수정 락을 획득한 경우, 다른 트랜잭션들은 해당 데이터에 접근할 수 없음
정 트랜잭션이 수정 트랜잭션을 의미하는 것인지 확인 부탁드리겠습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +Join은 데이터베이스에서 두 개 이상의 테이블을 연결하여 하나의 결과 집합을 생성하는 작업을 의미합니다. Join은 데이터베이스에서 데이터들을 효율적으로 검색하기 위해 사용되며, 특히 다양한 테이블에 분산되어 있는 데이터들을 필요에 맞게 결합할 때 매우 유용합니다.
해당 내용은 Join과 관련된 내용으로 Lock 부분보다 Join 부분에 작성하면 좋을 것 같습니다!

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +    * 테이블 자체를 삭제(DROP) 후 재생성(CREATE)의 개념
Truncate가 테이블을 삭제하는 것과는 차이가 있는 것으로 알고 있습니다!
내용 확인 부탁드리겠습니다!

참고 자료
https://lee-mandu.tistory.com/476

2023-07-31 00:21 UTC, HJ0216 commented on Database/database2.md
> +  * 이터베이스 관리 시스템(DBMS)에서 쿼리를 처리할 때, 가장 효율적인 실행 계획을 결정하는 역할을 담당하는 컴포넌트
이터베이스 → 데이터베이스
확인 부탁드리겠습니다!

2023-07-31 01:51 UTC, HJ0216 approved these changes

2023-07-31 01:51 UTC, HJ0216 commented on Database/database2.md
> +  * 테이블이 단순해지고 관리 효율성이 증가되나 데이터의 일관성이나 무결성이 보장지 않을 수 있음
보장지 → 보장되지
확인 부탁드리겠습니다!

2023-07-31 01:55 UTC, merged