Docs: add [Database]interview_list.md
Gabozago-Study/CS-Gabozago pull request #16
Opened 2023-07-30 15:17 UTC by busymidnight

## 개요
Docs: add [Database]interview_list.md 

## 작업사항
- Database Interview List 작성

## 변경사항

2023-07-30 15:59 UTC, leemyunga approved these changes

2023-07-30 15:59 UTC, leemyunga commented on InterviewList/[Database]interview_list.md
> +이렇듯 트랜잭션은 ACID 특징을 준수하여 데이터베이스의 안정성과 신뢰성을 확보하는 중요한 개념입니다.
ACID 특징을 준수함으로써 데이터베이스는 안정성과 신뢰성을 확보하며, 장애나 오류 시 데이터의 무결성과 일관성을 유지할 수 있습니다

라는 내용이 덧붙여지면 좋겠습니다

2023-07-31 00:38 UTC, HJ0216 requested changes

2023-07-31 00:38 UTC, HJ0216 commented on InterviewList/[Database]interview_list.md
> +
정규화의 단점도 추가되면 좋을 것 같습니다!

* 릴레이션의 분해로 인해 릴레이션 간의 연산(JOIN 연산)이 많아져 질의에 대한 응답 시간이 느려질 수 있음
* 성능을 향상 시키기 위해 인덱스 튜닝, 파티셔닝, 반정규화 등을 수행

2023-07-31 00:38 UTC, HJ0216 commented on InterviewList/[Database]interview_list.md
> +<br>
View에 대한 내용도 추가되면 좋을 것 같습니다!

2023-07-31 02:39 UTC, busymidnight commented
@HJ0216 수정 완료했습니다.

2023-07-31 02:41 UTC, HJ0216 approved these changes

2023-07-31 04:33 UTC, merged