Docs : design_pattern1.md
Gabozago-Study/CS-Gabozago pull request #17
Opened 2023-08-06 07:08 UTC by leemyunga

## 개요
Docs : design_pattern1.md

## 작업사항
- Design Pattern 정의
- 생성, 구조, 행위 패턴에 따른 분류 및 대표적인 패턴 상세

2023-08-06 08:42 UTC, HJ0216 requested changes

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +> |Singleton 싱글톤| 어떤 클래스의 인스턴스는 하나임을 보장하고 어디서든 참조할 수 있도록 함구조 패턴 |
구조 패턴 삭제 확인 부탁드립니다!

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +* 행위 패턴은 하나의 객체로 수행할 수 없는 작업을 여러 객체로 분배하면서 그들 간의 결합도를 최소화 할 수 있도록 도와준다.
명사형으로 모든 문장이 종료되어서 같이 맞춰주실 수 있으실까요?
도와준다. → 도와줌

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +* 행위 클래스 패턴은 상속을 통해 알고리즘과 제어 흐름을 기술하고, 행위 객체 해턴은 하나의 작업을 수행하기 위해 객체 집합이 어떻게 협력하는지를 기술
오타 확인 부탁드립니다!
해턴은 → 패턴은

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +> |Chain of Responsibility 책임 연쇄 | 청을 받는 객체를 연쇄적으로 묶어 요청을 처리하는 객체를 만날 때까지 객체 Chain을 따라 요청을 전달 |
오타 확인 부탁드립니다!
청을 → 요청을

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +> |Command 커맨드 | 청을 객체의 형태로 캡슐화하여 재사용하거나 취소할 수 있도록 저장 |
오타 확인 부탁드립니다!
청을 → 요청을

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +* 알고리즘의 유연한 교체를 가능하게 하는 패턴 비슷한 동작을 하지만 다르게 구현되어 있는 행위(전략)들을 공통의 인터페이스를 구현하는 각각의 클래스로 구현하고, 동적으로 바꿀 수 있도록 하는 패턴
줄 바꿈이나 연결어가 필요할 것 같아 확인 부탁드립니다!

비슷한 동작을 하지만 다르게 구현되어 있는 행위(전략)들을 공통의 인터페이스를 구현하는 각각의 클래스로 구현하고, 동적으로 바꿀 수 있도록 하는 패턴

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +  *새로운 알고리즘을 추가하기 쉽고, 기존 알고리즘의 변경이 자식 클래스에 영향이 없음
띄어쓰기로 마크다운 문법이 적용되지 않아, 확인 부탁드립니다!
*새로운 → * 새로운

2023-08-06 08:42 UTC, HJ0216 commented on DesignPattern/design_pattern.md
> +  *새로운 알고리즘을 추가하기 쉽고, 기존 알고리즘의 변경이 자식 클래스에 영향이 없음
구문 해석이 혼동되어 수정가능하실까요?

기존 알고리즘의 변경이 자식 클래스에 영향이 없음
→ 기존 알고리즘의 변경이 자식 클래스에게 영향이 없음
or 기존 알고리즘이 변경되어도 자식 클래스에 영향을 미치지 않음

2023-08-06 12:44 UTC, leemyunga commented on DesignPattern/design_pattern.md
> +  *새로운 알고리즘을 추가하기 쉽고, 기존 알고리즘의 변경이 자식 클래스에 영향이 없음
항상 꼼꼼한 확인 감사합니당 🫡 수정 했습니다!!

2023-08-06 16:12 UTC, busymidnight requested changes

2023-08-06 16:12 UTC, busymidnight commented on DesignPattern/design_pattern.md
> +  * 일부 단계가 서브클래스에 의해 고정되어 있기 때문에 일부 단계를 동적으로 변경하는 것이 어려움
템플릿 메서드 패턴의 단점을 추가하면 좋을 것 같습니다.

* 알고리즘 구조가 복잡할수록 템플릿 로직 형태를 유지하기 어려워짐
* 로직에 변화가 생겨 상위 클래스를 수정할 때, 모든 서브 클래스의 수정이 필요 할수도 있음

2023-08-06 16:12 UTC, busymidnight commented on DesignPattern/design_pattern.md
> +
아래 내용 추가해주면 좋을 것 같습니다. 

Spring으로 개발을 할 때 Lombok의 @Builder Annotation를 사용하면 자동으로 Builder Pattern에 맞게 builder 클래스를 생성해줌

2023-08-06 23:36 UTC, HJ0216 approved these changes

2023-08-07 00:52 UTC, HJ0216 commented
파일명 수정부탁드리겠습니다!
design_pattern.md → design_pattern1.md

2023-08-07 02:20 UTC, busymidnight approved these changes

2023-08-07 04:18 UTC, merged