Docs: add [DesignPattern]interview_list.md
Gabozago-Study/CS-Gabozago pull request #18
Opened 2023-08-06 08:18 UTC by HJ0216

## 개요
Docs: add [DesignPattern]interview_list.md

## 작업사항
 [DesignPattern]interview_list.md 파일 작성

## 변경사항

2023-08-06 13:03 UTC, leemyunga approved these changes

2023-08-06 13:03 UTC, leemyunga commented on InterviewList/[DesignPattern]interview_list.md
> +각각의 알고리즘을 독립적인 클래스로 구현하기 때문에 코드를 재사용이 간편하고, 다른 알고리즘으로 교체하기가 쉬워 애플리케이션의 유연성과 확장성이 증가시킬 수 있습니다.
유연성과 확장성이 증가시킬 수 있습니다.
-> 유연성과 확장성을 증가시킬 수 있습니다.

2023-08-06 13:03 UTC, leemyunga commented on InterviewList/[DesignPattern]interview_list.md
> +각 역할이 분리되어 있으므로, 변경이 발생해도 다른 역할에 영향을 미치지 않아 수정이 쉽고 재사용을 편리하게 할 수 있습니다. 이 외에도 코드의 가독성을 높일 수 있습니다.
이 외에도 코드의 가독성을 높일 수 있습니다. 이 부분이 각 역할이 분리되어 있으므로, 와 이어지는 내용인지 별개인지 구분이 되면 좋을 것 같습니다!

-> 각 역할이 분리되어 있으므로, 변경이 발생해도 다른 역할에 영향을 미치지 않아 수정이 쉽고 재사용을 편리하게 할 수 있습니다. 이로 인해 코드의 가독성도 높아집니다.
or 
->각 역할이 분리되어 있으므로 변경이 발생해도 다른 역할에 영향을 미치지 않아 수정이 쉽고 재사용이 편리 합니다. 또한 코드의 가독성을 높일 수 있습니다.

2023-08-06 16:07 UTC, busymidnight requested changes

2023-08-06 16:07 UTC, busymidnight commented on InterviewList/[DesignPattern]interview_list.md
> +클래스의 인스턴스가 오직 하나만 생성되도록 보장하는 패턴으로, 자원을 절약할 수 있고 객체를 전역적으로 사용할 수 있어 공유가 쉽니다.
공유가 쉽니다. -> 공유가 쉽습니다.

2023-08-06 16:07 UTC, busymidnight commented on InterviewList/[DesignPattern]interview_list.md
> +### [Q] Singleton Pattern 특징
아래 장단점이 추가된 답변이면 좋을 것 같습니다!
장점: 메모리 사용이 최적화되어 메모리 낭비를 방지  
단점: 인스턴스가 공유되므로, 다른 객체 사이의 의존성이 높아질 수 있고 전역 상태 관리가 복잡해 질 수 있음, 다른 인스턴스를 상속하거나 확장하기 어려울 수 있으며 상속이 불가능한 클래스일 경우 싱글톤 패턴을 사용할 수 없음

2023-08-06 16:07 UTC, busymidnight commented on InterviewList/[DesignPattern]interview_list.md
> +각각의 알고리즘을 독립적인 클래스로 구현하기 때문에 코드를 재사용이 간편하고, 다른 알고리즘으로 교체하기가 쉬워 애플리케이션의 유연성과 확장성이 증가시킬 수 있습니다.
각각의 알고리즘을 독립적인 클래스로 구현해야 하므로, 전략의 개수가 많을 경우 클래스의 수가 증가할 수 있는 단점도 있음을 언급하면 좋을 것 같습니다.

2023-08-06 16:07 UTC, busymidnight commented on InterviewList/[DesignPattern]interview_list.md
> +코드의 중복을 최소화할 수 있으며, 새로운 알고리즘을 추가하기 쉬워 확장성이 좋습니다.
템플릿 메서드 패턴의 단점도 추가하면 좋을 것 같습니다.
* 알고리즘 구조가 복잡할수록 템플릿 로직 형태를 유지하기 어려워짐
* 로직에 변화가 생겨 상위 클래스를 수정할 때, 모든 서브 클래스의 수정이 필요 할수도 있음

2023-08-06 16:07 UTC, busymidnight commented on InterviewList/[DesignPattern]interview_list.md
> +#
아래 질문 추가하면 좋을 것 같습니다.

[ Q ] 프로젝트에서 적용하지 못했던 객체 지향 설계 원칙이 있다면? 어떻게 리팩토링 할 건지

2023-08-07 02:21 UTC, busymidnight approved these changes

2023-08-08 00:04 UTC, merged