Docs: add Interview List files for Java and Spring
Gabozago-Study/CS-Gabozago pull request #9
Opened 2023-07-09 11:08 UTC by HJ0216

## 개요
week 02 - Interview list for Java and Spring

## 작업사항
자바 및 스프링 인터뷰 리스트 작성

## 변경사항
파일 이름 중복방지를 위해 파일명 변경
java.md → java_hj.md
spring.md → spring_hj.md

2023-07-09 11:33 UTC, busymidnight requested changes

2023-07-09 11:33 UTC, busymidnight commented on InterviewList/[Java]interview_list.md
> +`==`는 참조 비교 방식으로 같은 주소를 가르키고 있는지 확인합니다. 모든 기본 유형(Primitive Types)에 대해 적용할 수 있습니다.
가르키고 -> 가리키고
오타가 있습니다!

2023-07-09 11:37 UTC, busymidnight approved these changes

2023-07-09 11:40 UTC, HJ0216 commented on InterviewList/[Java]interview_list.md
> +`==`는 참조 비교 방식으로 같은 주소를 가르키고 있는지 확인합니다. 모든 기본 유형(Primitive Types)에 대해 적용할 수 있습니다.
오탈자 수정하였습니다!

2023-07-10 00:27 UTC, leemyunga approved these changes

2023-07-10 00:38 UTC, merged